
[basic]
host = 0.0.0.0
port = 10981
cpu_core = 3
debug = False
# prefix = 

file_based_job = True
clean_start = True

input_file_folder = input
allowed_file_ext = pdf, png, jpg, jpeg

template_folder = templates
static_folder = static
home_page = home.html
file_upload_finished_page = result.html

[GlyImageExtractor]
# Default options shown, commented

# pipeline types - default are already present in subclasses and
# ini file keys can override them using the below keys.
# also GlyImageExtractor.local.ini file can be used for testing with other pipelines
single_image_pipeline = SingleGlycanImage-YOLOFinders
multi_image_pipeline = MultipleGlycanImage-YOLOFindersV5

# options: fitz, figcap, hybrid (combination fo fitz + figcap)
# setting an image_search_strategy here - means you will be setting it for all PDF based job classes
# Note: Synethtic PDF jobs use fitz (which should never be updated) - so the setting image_search_strategy here wont change the default 'fitz' for synthetic jobs
image_search_strategy = hybrid

# Developer email
#
# dev_email = nje5+extractor@georgetown.edu
#

# Glyomics search URLs end in /
# 
# glymage_url = https://glymage.glyomics.org/
# glylookup_url = https://glylookup.glyomics.org/
# subsumption_url = https://subsumption.glyomics.org/
#

# Google analytics production URL string match
# 
# google_analytics_id = G-47WSZ1WYRZ
# google_analytics_url_match = extractor.glyomics.org
#
