
[basic]
host = 0.0.0.0
port = 10981
cpu_core = 3
# debug = False
# prefix = tandem10981

file_based_job = True
clean_start = True

input_file_folder = input
allowed_file_ext = pdf, png, jpg, jpeg

template_folder = templates
static_folder = static
home_page = home.html
file_upload_finished_page = result.html

[GlyImageExtractor]
# Default options shown, commented

# options: fitz, figcap, hybrid (combination fo fitz + figcap)
# image_search_type = fitz
#
image_search_type = hybrid

# Developer email
#
# dev_email = nje5+extractor@georgetown.edu
#

# Glyomics search URLs end in /
# 
# glymage_url = https://glymage.glyomics.org/
# glylookup_url = https://glylookup.glyomics.org/
# subsumption_url = https://subsumption.glyomics.org/
#

# Google analytics production URL string match
# 
# google_analytics_id = G-47WSZ1WYRZ
# google_analytics_url_match = extractor.glyomics.org
#
