[Pipeline:GlycanCompare-YOLOFinders]
figure_steps = SingleGlycanImage 
glycan_steps = YOLOMonosRandom,YOLORootFinder,ConnectYOLOBig

[Pipeline:GlycanCompare-YOLOFindersBiased]
figure_steps = SingleGlycanImage 
glycan_steps = YOLOMonosBiased,YOLORootFinder,ConnectYOLOBig

[Pipeline:GlycanCompare-YOLOFindersInfo_v0]
figure_steps = SingleGlycanImage 
glycan_steps = YOLOMonosRandom,YOLORootFinder,ConnectYOLOLinkage_v0

[Pipeline:GlycanCompare-YOLOFindersInfo_v1]
figure_steps = SingleGlycanImage 
glycan_steps = YOLOMonosRandom,YOLORootFinder,ConnectYOLOLinkage_v1

[Pipeline:GlycanCompare-YOLOFindersInfo_v2]
figure_steps = SingleGlycanImage 
glycan_steps = YOLOMonosRandom,YOLORootFinder,ConnectYOLOLinkage_v2

[Pipeline:GlycanCompare-KnownFinders]
figure_steps = SingleGlycanImage
glycan_steps = KnownMono,KnownRoot,KnownLink

[Pipeline:GlycanCompare-KnownFindersInfo]
figure_steps = SingleGlycanImage
glycan_steps = KnownMono,KnownRoot,KnownLinkWithInfo

# Pipeline for WebApplication
[Pipeline:SingleGlycanImage-YOLOFinders]
figure_steps = SingleGlycanImage,CleanImage
glycan_steps = YOLOMonosBiased_V4,YOLORootFinder,YOLOLinksFilter

# Pipeline for WebApplication
[Pipeline:MultipleGlycanImage-YOLOFinders]
figure_steps = OriginalYOLO,CleanImage 
glycan_steps = YOLOMonosBiased_V4,YOLORootFinder,YOLOLinksFilter

[Pipeline:SingleGlycanImage-YOLOFinders_linkage_1000]
figure_steps = SingleGlycanImage 
glycan_steps = YOLOMonosRandom,YOLORootFinder,ConnectYOLOLinkage_1000

[Pipeline:SingleGlycanImage-YOLOFinders_linkage_5000]
figure_steps = SingleGlycanImage 
glycan_steps = YOLOMonosRandom,YOLORootFinder,ConnectYOLOLinkage_v1

[Pipeline:SingleGlycanImage-YOLOFinders_linkage_v2_9000]
figure_steps = SingleGlycanImage 
glycan_steps = YOLOMonosRandom,YOLORootFinder,ConnectYOLOLinkage_v2

[Pipeline:SingleGlycanImage-YOLOFinders_linkage_balanced_45k_20k]
figure_steps = SingleGlycanImage 
glycan_steps = YOLOMonosRandom,YOLORootFinder,ConnectYOLOLinkage_v3 # changed name

[Pipeline:SingleGlycanImage-YOLOFinders_linkage_balanced_overwritten_33k]
figure_steps = SingleGlycanImage 
glycan_steps = YOLOMonosRandom,YOLORootFinder,balanced_overwritten

[Pipeline:KnownSemantics]
figure_steps = SingleGlycanImage
glycan_steps = KnownMono,KnownRoot,KnownLink

[Pipeline:KnownSemanticsWithInfo]
figure_steps = SingleGlycanImage
glycan_steps = KnownMono,KnownRoot,KnownLinkWithInfo

[Pipeline:OriginalAnnotator]
figure_steps = SingleGlycanImage
glycan_steps = HeuristicMonos, OriginalConnector, DefaultOrientationRootFinder

[Pipeline:YOLOOrientationAnnotator]
figure_steps = SingleGlycanImage
glycan_steps = HeuristicMonos, OriginalConnector, YOLOOrientationRootFinder

[Pipeline:YOLORootFinderAnnotator]
figure_steps = SingleGlycanImage
glycan_steps = HeuristicMonos, OriginalConnector, YOLORootFinder

[Pipeline:YOLOMonosPlusOrientationAnnotator]
figure_steps = SingleGlycanImage
glycan_steps = YOLOMonosRandom, OriginalConnector, YOLOOrientationRootFinder

[Pipeline:YOLOMonosPlusRootFinderAnnotator]
figure_steps = SingleGlycanImage
glycan_steps = YOLOMonosRandom, OriginalConnector, YOLORootFinder

[Pipeline:YOLOGlycanFinder]
figure_steps = OriginalYOLO

[Pipeline:KnownGlycanBoxes]
figure_steps = KnownGlycanBoxes

[Finder:CleanImage]
class=CleanGlycanImage

[Finder:YOLO_Glycan]
class=YOLO_Glycan
label_type=composition

[Finder:Known_Glycan]
class=Known_Glycan
label_type=composition

[Finder:SingleGlycanImage]
class=SingleGlycanImage
crop=false

[Finder:OriginalYOLO]
class=YOLOGlycanFinder
weights=largerboxes_plusindividualglycans.weights
config=coreyolo.cfg
iou_threshold=0.5
conf_threshold=0.5
; expandimage=100
; boxpadding=50

[Finder:YOLOMonosRandom]
class=YOLOMonos
config=monos2.cfg
weights=yolov3_monos_random.weights
expandimage=0
boxpadding=0
iou_threshold=0.4
conf_threshold=0.8

# simple biased, default LR
[Finder:YOLOMonosBiased_V1]
class=YOLOMonos
config=yolov3_biased_v1.cfg
weights=yolov3_biased_v1.weights
expandimage=0
boxpadding=0
iou_threshold=0.4
conf_threshold=0.8

# simple biased - trained again - I changed max_steps and steps but kept default LR
[Finder:YOLOMonosBiased_V2]
class=YOLOMonos
config=yolov3_biased_v2.cfg
weights=yolov3_biased_v2.weights
expandimage=0
boxpadding=0
iou_threshold=0.4
conf_threshold=0.8

# simple biased - learning rate: 0.0005
[Finder:YOLOMonosBiased_V3]
class=YOLOMonos
config=yolov3_biased_v3.cfg
weights=yolov3_biased_v3.weights
expandimage=0
boxpadding=0
iou_threshold=0.4
conf_threshold=0.8

# random biased, default LR
[Finder:YOLOMonosBiased_V4]
class=YOLOMonos
config=yolov3_biasedmono_v4.cfg
weights=yolov3_biasedmono_v4.weights
expandimage=0
boxpadding=0
iou_threshold=0.4
conf_threshold=0.8

# random baised - learning rate: 0.0005
[Finder:YOLOMonosBiased_V5]
class=YOLOMonos
config=yolov3_biasedmono_v5.cfg
weights=yolov3_biasedmono_v5.weights
expandimage=0
boxpadding=0
iou_threshold=0.4
conf_threshold=0.8

[Finder:ConnectYOLO]
class=ConnectYOLO
config=yolov3_small.cfg
weights=yolov3_small_final.weights
expandimage=0
boxpadding=0
iou_threshold=0.5


[Finder:ConnectYOLOBig]
class=ConnectYOLO
config=yolov3_big.cfg
weights=yolov3_big_final.weights
expandimage=0
boxpadding=0
iou_threshold=0.5
conf_threshold=0.75

[Finder:YOLOLinksFilter]
class=YOLOLinksFilter
config=yolov3_big.cfg
weights=yolov3_big_final.weights
expandimage=0
boxpadding=0
iou_threshold=0.5
conf_threshold=0.75

[Finder:ConnectYOLOLinkage_v0] #ConnectYOLOLinakge_1000 (campbell)
class=ConnectYOLOInfo
config=linkage/yolov3_linkage_1000.cfg
weights=linkage/yolov3_linkage_1000.weights
expandimage=0
boxpadding=3
iou_threshold=0.5
conf_threshold=0.75

[Finder:ConnectYOLOLinkage_v1] #ConnectYOLOLinkage_5000
class=ConnectYOLOInfo
config=linkage/yolov3_linkage_5000.cfg
weights=linkage/yolov3_linkage_5000.weights
expandimage=0
boxpadding=3
iou_threshold=0.5
conf_threshold=0.75

[Finder:v2_9k] #ConnectYoloLinkage_v2_9000
class=ConnectYOLOInfo
config=linkage/yolov3_linkage_v2_9000.cfg
weights=linkage/yolov3_linkage_v2_9000.weights
expandimage=0
boxpadding=3
iou_threshold=0.5
conf_threshold=0.75


[Finder:v2_1k] #ConnectYoloLinkage_v2_1k
class=ConnectYOLOInfo
config=linkage/yolov3_linkage_v2_1k.cfg
weights=linkage/yolov3_linkage_v2_1k.weights
expandimage=0
boxpadding=3
iou_threshold=0.5
conf_threshold=0.75

[Finder:v2_5k] #ConnectYoloLinkage_v2_5k
class=ConnectYOLOInfo
config=linkage/yolov3_linkage_v2_5k.cfg
weights=linkage/yolov3_linkage_v2_5k.weights
expandimage=0
boxpadding=3
iou_threshold=0.5
conf_threshold=0.75

[Finder:v2_10k] #ConnectYoloLinkage_v2_10k
class=ConnectYOLOInfo
config=linkage/yolov3_linkage_v2_10k.cfg
weights=linkage/yolov3_linkage_v2_10k.weights
expandimage=0
boxpadding=3
iou_threshold=0.5
conf_threshold=0.75

[Finder:v2_20k] # yolov3_linkage_v2_20k
class=ConnectYOLOInfo
config=linkage/yolov3_linkage_v2_20k.cfg
weights=linkage/yolov3_linkage_v2_20k.weights
expandimage=0
boxpadding=3
iou_threshold=0.5
conf_threshold=0.75

[Finder:v2_40k] # yolov3_linkage_v2_40k
class=ConnectYOLOInfo
config=linkage/yolov3_linkage_v2_40k.cfg
weights=linkage/yolov3_linkage_v2_40k.weights
expandimage=0
boxpadding=3
iou_threshold=0.5
conf_threshold=0.75

[Finder:uniform20k_rand1k] # yolov3_linkage_uniform20k_rand1k
class=ConnectYOLOInfo
config=linkage/yolov3_linkage_uniform20k_rand1k.cfg
weights=linkage/yolov3_linkage_uniform20k_rand1k.weights
expandimage=0
boxpadding=3
iou_threshold=0.5
conf_threshold=0.75

[Finder:v2uniform20k_rand4k] # yolov3_linkage_uniform20k_rand4k
class=ConnectYOLOInfo
config=linkage/yolov3_linkage_v2uniform20k_rand4k.cfg
weights=linkage/yolov3_linkage_v2uniform20k_rand4k.weights
expandimage=0
boxpadding=3
iou_threshold=0.5
conf_threshold=0.75

[Finder:v2uniform20k_rand10k] # yolov3_linkage_uniform20k_rand10k
class=ConnectYOLOInfo
config=linkage/yolov3_linkage_v2uniform20k_rand10k.cfg
weights=linkage/yolov3_linkage_v2uniform20k_rand10k.weights
expandimage=0
boxpadding=3
iou_threshold=0.5
conf_threshold=0.75

[Finder:v2uniform20k_rand1k_xx4k] # yolov3_linkage_v2uniform20k_rand1k_xx4k
class=ConnectYOLOInfo
config=linkage/yolov3_linkage_v2uniform20k_rand1k_xx4k.cfg
weights=linkage/yolov3_linkage_v2uniform20k_rand1k_xx4k.weights
expandimage=0
boxpadding=3
iou_threshold=0.5
conf_threshold=0.75


#[Finder:partly_balanced] # ConnectYOLOLinkage_balanced_45k_20k
#class=ConnectYOLOInfo
#config=yolov3_linkage_balanced_45k_20k.cfg
#weights=yolov3_linkage_balanced_45k_20k.weights
#expandimage=0
#boxpadding=3
#iou_threshold=0.5
#conf_threshold=0.75

#[Finder:balanced_overwritten] # ConnectYOLOLinkage_balanced_overwritten_33k
#class=ConnectYOLOInfo
#config=yolov3_linkage_balanced_overwritten_33k.cfg
#weights=yolov3_linkage_balanced_overwritten_33k.weights
#expandimage=0
#boxpadding=3
#iou_threshold=0.5
#conf_threshold=0.75

#[Finder:exponential_distribution] # linkage exp_dist_experimental_20k (campbell)
#class=ConnectYOLOInfo
#config=yolov3_exp_dist_experimental_20k.cfg
#weights=yolov3_exp_dist_experimental_20k.weights
#expandimage=0
#boxpadding=3
#iou_threshold=0.5
#conf_threshold=0.75

#[Finder:randlink_20k] # campbell
#class=ConnectYOLOInfo
#config=yolov3_randlink_20k.cfg
#weights=yolov3_randlink_20k.weights
#expandimage=0
#boxpadding=3
#iou_threshold=0.5
#conf_threshold=0.75


[Finder:YOLORootFinder]
class=YOLORootFinder
config=rootmono.cfg
weights=yolov3_rootmono.weights
iou_threshold=0.2
boxpadding=5

[Finder:CurrentBuilder]
class=RootedTreeBuilder

[Finder:SearchGlycoCT]
class=SearchGlycoCT

[Finder:SendToGNOme]
class=SendToGNOme

[Finder:KnownGlycanBoxes]
class=KnownGlycanBoxes
# 20% padding
boxpadding=0.2

[Finder:KnownMono]
class=KnownMono
boxpadding=5

[Finder:KnownLink]
class=KnownLink
boxpadding=3

[Finder:KnownLinkWithInfo]
class=KnownLinkWithInfo
boxpadding=3

[Finder:KnownRoot]
class=KnownRoot
boxpadding=0

[Finder:HeuristicMonos]
color_range=colors_range.txt
class=HeuristicMonos

[Finder:YOLOMonosLargerBoxes]
class=YOLOMonos
color_range=colors_range.txt
weights=yolov3_monos_largerboxes.weights
config=monos2.cfg

[Finder:OriginalConnector]
color_range=colors_range.txt
class=OriginalConnector

[Finder:DefaultOrientationRootFinder]
class=DefaultOrientationRootFinder

[Finder:YOLOOrientationRootFinder]
weights=orientation_flipped.weights
config=orientation_flipped.cfg
class=YOLOOrientationRootFinder
