[Pipeline:GlycanCompare-YOLOFinders]
figure_steps = SingleGlycanImage 
glycan_steps = YOLOMonosRandom,YOLORootFinder,ConnectYOLOBig,YOLOGlycan

[Pipeline:GlycanCompare-YOLO58Finders]
figure_steps = SingleGlycanImage 
glycan_steps = YOLOMono_58,YOLORedEnd_58,YOLOLink_58,YOLOGlycan

[Pipeline:GlycanCompare-YOLOFindersBiased]
figure_steps = SingleGlycanImage 
glycan_steps = YOLOMonosBiased_V1,YOLORootFinder,ConnectYOLOBig,YOLOGlycan

[Pipeline:GlycanCompare-KnownFinders]
figure_steps = SingleGlycanImage
glycan_steps = KnownMono,KnownRoot,KnownLink,KnownGlycan

# added YOLOGlycanNoLabel finder to the pipeline which sets the IUPAC and composition and noLabel
# wont set a classlabel (otherwise classlabel iupac or composition can be used)

# WebApplication pipeline naming convention <PipelineType>-<Name> 
# follow convention, so that if a pipeline needs to be overriden by the GlyImageExtractor.ini file
# its easier to differentiate between Single and Multi glycan image
# Pipeline for WebApplication
[Pipeline:SingleGlycanImage-YOLOFinders]
figure_steps = SingleGlycanImage
glycan_steps = YOLOMono_58,YOLORedEnd_58,YOLOLink_58,YOLOGlycanNoLabel

# Pipeline for WebApplication
[Pipeline:MultipleGlycanImage-YOLOFinders]
figure_steps = OriginalYOLO,CleanImage 
glycan_steps = YOLOMono_58,YOLORedEnd_58,YOLOLink_58,YOLOGlycanNoLabel

# Pipeline for WebApplication - glycan finder was trained with a padding = 10
[Pipeline:MultipleGlycanImage-YOLOFindersV2]
figure_steps = Glycan_all_training_v3,CleanImage 
glycan_steps = YOLOMono_58,YOLORedEnd_58,YOLOLink_58,YOLOGlycanNoLabel

# Pipeline for WebApplication - glycan finder was trained with no padding
[Pipeline:MultipleGlycanImage-YOLOFindersV3]
figure_steps = Glycan_all_training_nopad_v2,CleanImage
glycan_steps = YOLOMono_58,YOLORedEnd_58,YOLOLink_58,YOLOGlycanNoLabel

[Pipeline:MultipleGlycanImage-YOLOFindersV4]
figure_steps = Glycan_all_training_nopad_v2,CleanImage_NoBackGround
glycan_steps = YOLOMono_58,YOLORedEnd_58,YOLOLink_58,YOLOGlycanNoLabel

[Pipeline:MultipleGlycanImage-YOLOFindersV5]
figure_steps = Glycan_all_training_nopad_v2,CleanImage_NoBackGroundV2
glycan_steps = YOLOMono_58,YOLORedEnd_58,YOLOLink_58,YOLOGlycanNoLabel

[Pipeline:SingleGlycanImage-YOLOFinders_linkage_1000]
figure_steps = SingleGlycanImage 
glycan_steps = YOLOMonosRandom,YOLORootFinder,ConnectYOLOLinkage_1000

[Pipeline:SingleGlycanImage-YOLOFinders_linkage_5000]
figure_steps = SingleGlycanImage 
glycan_steps = YOLOMonosRandom,YOLORootFinder,ConnectYOLOLinkage_5000,YOLOGlycan

[Pipeline:KnownSemantics]
figure_steps = SingleGlycanImage
glycan_steps = KnownMono,KnownRoot,KnownLink,KnownGlycan

[Pipeline:KnownSemanticsWithInfo]
figure_steps = SingleGlycanImage
glycan_steps = KnownMono,KnownRoot,KnownLinkWithInfo,KnownGlycan

[Pipeline:OriginalAnnotator]
figure_steps = SingleGlycanImage
glycan_steps = HeuristicMonos, OriginalConnector, DefaultOrientationRootFinder

[Pipeline:YOLOOrientationAnnotator]
figure_steps = SingleGlycanImage
glycan_steps = HeuristicMonos, OriginalConnector, YOLOOrientationRootFinder

[Pipeline:YOLORootFinderAnnotator]
figure_steps = SingleGlycanImage
glycan_steps = HeuristicMonos, OriginalConnector, YOLORootFinder

[Pipeline:YOLOMonosPlusOrientationAnnotator]
figure_steps = SingleGlycanImage
glycan_steps = YOLOMonosRandom, OriginalConnector, YOLOOrientationRootFinder

[Pipeline:YOLOMonosPlusRootFinderAnnotator]
figure_steps = SingleGlycanImage
glycan_steps = YOLOMonosRandom, OriginalConnector, YOLORootFinder

[Pipeline:SingleGlycanImage]
figure_steps = SingleGlycanImage
glycan_steps = 

[Pipeline:YOLOGlycanFinder]
figure_steps = OriginalYOLO

[Pipeline:KnownGlycanBoxes]
figure_steps = KnownGlycanBoxes

[Finder:CleanImage]
class=CleanGlycanImage

[Finder:CleanImage_NoBackGround]
class=CleanGlycanImage
remove_background=True

[Finder:CleanImage_NoBackGroundV2]
class=CleanGlycanImageV2
remove_background=True

[Finder:YOLOGlycan]
class=YOLO_Glycan
label_type=iupac

[Finder:YOLOGlycanNoLabel]
class=YOLO_Glycan

[Finder:KnownGlycan]
class=Known_Glycan
label_type=iupac

[Finder:SingleGlycanImage]
class=SingleGlycanImage
crop=false

[Finder:YOLOGlycan_v6]
# YOLOGlycanRetrain glycan_v6
# --config yolov4 -iou_thresh 0.85 -thresh 0.9
# --max_batches 50000
class=YOLOGlycanFinder
weights=glycan/glycan_v6.weights
config=glycan/glycan_v6.cfg
iou_threshold=0.5
conf_threshold=0.5
; expandimage=100
; boxpadding=0.1

[Finder:OriginalYOLO]
class=YOLOGlycanFinder
weights=glycan/largerboxes_plusindividualglycans.weights
config=glycan/coreyolo.cfg
iou_threshold=0.5
conf_threshold=0.5
; expandimage=100
; boxpadding=50

[Finder:Glycan_all_training_v3]
class=YOLOGlycanFinder
weights=glycan/all_manuscripts_plusindividuals_yolov4_default_gly_v3.weights
config=glycan/all_manuscripts_plusindividuals_yolov4_default_gly_v3.cfg
iou_threshold=0.5
conf_threshold=0.5

[Finder:Glycan_all_training_nopad_v2]
class=YOLOGlycanFinder
weights=glycan/all_manuscripts_plusindividuals_yolov4_nopad_dg_v2.weights
config=glycan/all_manuscripts_plusindividuals_yolov4_nopad_dg_v2.cfg
iou_threshold=0.5
conf_threshold=0.5

[Finder:YOLOMonosRandom]
class=YOLOMonos
config=mono/monos2.cfg
weights=mono/yolov3_monos_random.weights
expandimage=0
boxpadding=0
iou_threshold=0.4
conf_threshold=0.8

# simple biased, default LR
[Finder:YOLOMonosBiased_V1]
class=YOLOMonos
config=mono/yolov3_biased_v1.cfg
weights=mono/yolov3_biased_v1.weights
expandimage=0
boxpadding=0
iou_threshold=0.4
conf_threshold=0.8

# simple biased - trained again - I changed max_steps and steps but kept default LR
[Finder:YOLOMonosBiased_V2]
class=YOLOMonos
config=mono/yolov3_biased_v2.cfg
weights=mono/yolov3_biased_v2.weights
expandimage=0
boxpadding=0
iou_threshold=0.4
conf_threshold=0.8

# simple biased - learning rate: 0.0005
[Finder:YOLOMonosBiased_V3]
class=YOLOMonos
config=mono/yolov3_biased_v3.cfg
weights=mono/yolov3_biased_v3.weights
expandimage=0
boxpadding=0
iou_threshold=0.4
conf_threshold=0.8

# random biased, default LR
[Finder:YOLOMonosBiased_V4]
class=YOLOMonos
config=mono/yolov3_biasedmono_v4.cfg
weights=mono/yolov3_biasedmono_v4.weights
expandimage=0
boxpadding=0
iou_threshold=0.4
conf_threshold=0.8

# random baised - learning rate: 0.0005
[Finder:YOLOMonosBiased_V5]
class=YOLOMonos
config=mono/yolov3_biasedmono_v5.cfg
weights=mono/yolov3_biasedmono_v5.weights
expandimage=0
boxpadding=0
iou_threshold=0.4
conf_threshold=0.8

[Finder:YOLOMono_58]
# YOLOMono-Biased-10k-2025-10-28 mono_v5_8
# --config yolov4-tiny -iou_thresh 0.85 -thresh 0.9
# --max_batches 30000
weights=yolo58/mono_v5_8.weights
config=yolo58/mono_v5_8.cfg
class=YOLOMonos
expandimage=0
boxpadding=0
iou_threshold=0.4
conf_threshold=0.8


[Finder:ConnectYOLO]
class=ConnectYOLO
config=linkage/yolov3_small.cfg
weights=linkage/yolov3_small_final.weights
expandimage=0
boxpadding=0
iou_threshold=0.5


[Finder:ConnectYOLOBig]
class=ConnectYOLO
config=linkage/yolov3_big.cfg
weights=linkage/yolov3_big_final.weights
expandimage=0
boxpadding=0
iou_threshold=0.5
conf_threshold=0.75

[Finder:YOLOLink_58]
# YOLOLinkNoLink-Biased-10k-2025-10-28 link_v5_8
# --config yolov4-tiny -iou_thresh 0.85 -thresh 0.9
# --max_batches 30000
weights=yolo58/link_v5_8.weights
config=yolo58/link_v5_8.cfg
class=ConnectYOLO
expandimage=0
boxpadding=0
iou_threshold=0.75
conf_threshold=0.25

[Finder:ConnectYOLOLinkage_1000]
class=ConnectYOLOInfo
config=linkinfo/yolov3_linkage_1000.cfg
weights=linkinfo/yolov3_linkage_1000.weights
expandimage=0
boxpadding=3
iou_threshold=0.5
conf_threshold=0.75

[Finder:ConnectYOLOLinkage_5000]
class=ConnectYOLOInfo
config=linkinfo/yolov3_linkage_5000.cfg
weights=linkinfo/yolov3_linkage_5000.weights
expandimage=0
boxpadding=3
iou_threshold=0.5
conf_threshold=0.75

[Finder:YOLORootFinder]
class=YOLORootFinder
config=root/rootmono.cfg
weights=root/yolov3_rootmono.weights
iou_threshold=0.2
boxpadding=5


[Finder:YOLORedEnd_58]
# YOLORedEnd-Biased-10k-2025-10-28 redend_v5_8
# --config yolov4-tiny -iou_thresh 0.85 -thresh 0.9
# --max_batches 30000
weights=yolo58/redend_v5_8.weights
config=yolo58/redend_v5_8.cfg
class=YOLORootFinder
expandimage=0
boxpadding=0
iou_threshold=0.4
conf_threshold=0.5

[Finder:CurrentBuilder]
class=RootedTreeBuilder

[Finder:SearchGlycoCT]
class=SearchGlycoCT

[Finder:SendToGNOme]
class=SendToGNOme

[Finder:KnownGlycanBoxes]
class=KnownGlycanBoxes
# 20% padding
# boxpadding=0.20

[Finder:KnownMono]
class=KnownMono
boxpadding=5

[Finder:KnownLink]
class=KnownLink
boxpadding=3

[Finder:KnownLinkNoLink]
class=KnownLinkNoLink
boxpadding=3

[Finder:KnownLinkWithInfo]
class=KnownLinkWithInfo
boxpadding=3

[Finder:KnownRoot]
class=KnownRoot
boxpadding=0

[Finder:HeuristicMonos]
color_range=colors_range.txt
class=HeuristicMonos

[Finder:YOLOMonosLargerBoxes]
class=YOLOMonos
color_range=colors_range.txt
weights=mono/yolov3_monos_largerboxes.weights
config=mono/monos2.cfg

[Finder:OriginalConnector]
color_range=colors_range.txt
class=OriginalConnector

[Finder:DefaultOrientationRootFinder]
class=DefaultOrientationRootFinder

[Finder:YOLOOrientationRootFinder]
weights=root/orientation_flipped.weights
config=root/orientation_flipped.cfg
class=YOLOOrientationRootFinder

