[Pipeline:GlycanCompare-YOLOFinders]
figure_steps = SingleGlycanImage 
glycan_steps = YOLOMonosRandom,YOLORootFinder,ConnectYOLOBig

[Pipeline:GlycanCompare-YOLOFindersBiased]
figure_steps = SingleGlycanImage 
glycan_steps = YOLOMonosBiased,YOLORootFinder,ConnectYOLOBig

[Pipeline:GlycanCompare-KnownFinders]
figure_steps = SingleGlycanImage
glycan_steps = KnownMono,KnownRoot,KnownLink

# Pipeline for WebApplication
[Pipeline:SingleGlycanImage-YOLOFinders]
figure_steps = SingleGlycanImage,CleanImage
glycan_steps = YOLOMonosBiased_V4,YOLORootFinder,YOLOLinksFilter

# Pipeline for WebApplication
[Pipeline:MultipleGlycanImage-YOLOFinders]
figure_steps = OriginalYOLO,CleanImage 
glycan_steps = YOLOMonosBiased_V4,YOLORootFinder,YOLOLinksFilter

[Pipeline:KnownSemantics]
figure_steps = SingleGlycanImage
glycan_steps = KnownMono

[Pipeline:OriginalAnnotator]
figure_steps = SingleGlycanImage
glycan_steps = HeuristicMonos, OriginalConnector, DefaultOrientationRootFinder

[Pipeline:YOLOOrientationAnnotator]
figure_steps = SingleGlycanImage
glycan_steps = HeuristicMonos, OriginalConnector, YOLOOrientationRootFinder

[Pipeline:YOLORootFinderAnnotator]
figure_steps = SingleGlycanImage
glycan_steps = HeuristicMonos, OriginalConnector, YOLORootFinder

[Pipeline:YOLOMonosPlusOrientationAnnotator]
figure_steps = SingleGlycanImage
glycan_steps = YOLOMonosRandom, OriginalConnector, YOLOOrientationRootFinder

[Pipeline:YOLOMonosPlusRootFinderAnnotator]
figure_steps = SingleGlycanImage
glycan_steps = YOLOMonosRandom, OriginalConnector, YOLORootFinder

[Pipeline:YOLOGlycanFinder]
figure_steps = OriginalYOLO

[Pipeline:KnownGlycanBoxes]
figure_steps = KnownGlycanBoxes

[Finder:CleanImage]
class=CleanGlycanImage

[Finder:YOLO_Glycan]
class=YOLO_Glycan
label_type=composition

[Finder:Known_Glycan]
class=Known_Glycan
label_type=composition

[Finder:SingleGlycanImage]
class=SingleGlycanImage
crop=false

[Finder:OriginalYOLO]
class=YOLOGlycanFinder
weights=largerboxes_plusindividualglycans.weights
config=coreyolo.cfg
iou_threshold=0.5
conf_threshold=0.5
; expandimage=100
; boxpadding=50

[Finder:YOLOMonosRandom]
class=YOLOMonos
config=monos2.cfg
weights=yolov3_monos_random.weights
expandimage=0
boxpadding=0
iou_threshold=0.4
conf_threshold=0.8

# simple biased, default LR
[Finder:YOLOMonosBiased_V1]
class=YOLOMonos
config=yolov3_biased_v1.cfg
weights=yolov3_biased_v1.weights
expandimage=0
boxpadding=0
iou_threshold=0.4
conf_threshold=0.8

# simple biased - trained again - I changed max_steps and steps but kept default LR
[Finder:YOLOMonosBiased_V2]
class=YOLOMonos
config=yolov3_biased_v2.cfg
weights=yolov3_biased_v2.weights
expandimage=0
boxpadding=0
iou_threshold=0.4
conf_threshold=0.8

# simple biased - learning rate: 0.0005
[Finder:YOLOMonosBiased_V3]
class=YOLOMonos
config=yolov3_biased_v3.cfg
weights=yolov3_biased_v3.weights
expandimage=0
boxpadding=0
iou_threshold=0.4
conf_threshold=0.8

# random biased, default LR
[Finder:YOLOMonosBiased_V4]
class=YOLOMonos
config=yolov3_biasedmono_v4.cfg
weights=yolov3_biasedmono_v4.weights
expandimage=0
boxpadding=0
iou_threshold=0.4
conf_threshold=0.8

# random baised - learning rate: 0.0005
[Finder:YOLOMonosBiased_V5]
class=YOLOMonos
config=yolov3_biasedmono_v5.cfg
weights=yolov3_biasedmono_v5.weights
expandimage=0
boxpadding=0
iou_threshold=0.4
conf_threshold=0.8

[Finder:ConnectYOLO]
class=ConnectYOLO
config=yolov3_small.cfg
weights=yolov3_small_final.weights
expandimage=0
boxpadding=0
iou_threshold=0.5


[Finder:ConnectYOLOBig]
class=ConnectYOLO
config=yolov3_big.cfg
weights=yolov3_big_final.weights
expandimage=0
boxpadding=0
iou_threshold=0.5
conf_threshold=0.75

[Finder:YOLOLinksFilter]
class=YOLOLinksFilter
config=yolov3_big.cfg
weights=yolov3_big_final.weights
expandimage=0
boxpadding=0
iou_threshold=0.5
conf_threshold=0.75


[Finder:YOLORootFinder]
class=YOLORootFinder
config=rootmono.cfg
weights=yolov3_rootmono.weights
iou_threshold=0.2
boxpadding=5

[Finder:CurrentBuilder]
class=RootedTreeBuilder

[Finder:SearchGlycoCT]
class=SearchGlycoCT

[Finder:SendToGNOme]
class=SendToGNOme

[Finder:KnownGlycanBoxes]
class=KnownGlycanBoxes
# 20% padding
boxpadding=0.2

[Finder:KnownMono]
class=KnownMono
boxpadding=5

[Finder:KnownLink]
class=KnownLink
boxpadding=0

[Finder:KnownRoot]
class=KnownRoot
boxpadding=0

[Finder:HeuristicMonos]
color_range=colors_range.txt
class=HeuristicMonos

[Finder:YOLOMonosLargerBoxes]
class=YOLOMonos
color_range=colors_range.txt
weights=yolov3_monos_largerboxes.weights
config=monos2.cfg

[Finder:OriginalConnector]
color_range=colors_range.txt
class=OriginalConnector

[Finder:DefaultOrientationRootFinder]
class=DefaultOrientationRootFinder

[Finder:YOLOOrientationRootFinder]
weights=orientation_flipped.weights
config=orientation_flipped.cfg
class=YOLOOrientationRootFinder

