
import requests, urllib, traceback, sys, unicodedata
import xml.etree.ElementTree as ET

devemail = 'nje5+extractor@georgegetown.edu'

def lookup(doi=None,pmid=None,pmcid=None):
    baseurl = "https://pmc.ncbi.nlm.nih.gov/tools/idconv/api/v1/articles/"
    query = dict(tool="extractor",email=devemail,format="json")
    if pmid:
        query.update(dict(ids=pmid,idtype="pmid"))
    elif pmcid:
        query.update(dict(ids=pmcid,idtype="pmcid"))
    elif doi:
        query.update(dict(ids=doi,idtype="doi"))
    fullurl = baseurl + "?" + urllib.parse.urlencode(query)
    try:
        resp = requests.get(fullurl, timeout=5).json()
    except (requests.exceptions.Timeout,requests.exceptions.ReadTimeout,requests.exceptions.RequestException) as e:
        traceback.format_exc()
        resp = None
    if not resp or 'records' not in resp or len(resp['records']) != 1:
        return None
    record = resp['records'][0]
    if record.get('status') == 'error':
        return None
    return dict(doi=record['doi'],pmid=str(record['pmid']),pmcid=record['pmcid'])

# Generated by Gemini to solve the problem of embedded HTML 
# itaics markers <i> </i> in manuscript titles.

def get_unicode_italic(text):
    """Converts standard A-Z and a-z characters to Unicode Mathematical Italics."""
    if not text:
        return ""
    
    italic_map = {}
    # Map Uppercase A-Z to Unicode Mathematical Italic block
    for i, char_code in enumerate(range(65, 91)):
        italic_map[chr(char_code)] = chr(0x1D434 + i)
        
    # Map Lowercase a-z 
    for i, char_code in enumerate(range(97, 123)):
        if chr(char_code) == 'h':
            # 'h' is a Unicode exception (Planck constant)
            italic_map['h'] = '\u210E' 
        else:
            italic_map[chr(char_code)] = chr(0x1D44E + i)

    # Translate the characters, leaving non-alphabet characters untouched
    return "".join(italic_map.get(c, c) for c in text)

def extract_full_text(element):
    """Reconstructs the full text from an ElementTree element, italicizing <i> tags."""
    # 1. Start with the text before any child tags
    text_parts = [element.text or ""]
    
    # 2. Iterate through child elements
    for child in element:
        if child.tag == 'i':
            # Convert text inside <i> to Unicode italics
            italicized_text = get_unicode_italic(child.text)
            text_parts.append(italicized_text)
        else:
            # Handle other tags normally
            text_parts.append(child.text or "")
        
        # 3. Always append the tail (text immediately following the child tag)
        text_parts.append(child.tail or "")
        
    return "".join(text_parts)

def citation_details(pmid):
    baseurl = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi"
    query = dict(db="pubmed",id=pmid)
    fullurl = baseurl + "?" + urllib.parse.urlencode(query)
    # print(fullurl)
    try:
        resp = requests.get(fullurl, timeout=5)
    except (requests.exceptions.Timeout,requests.exceptions.ReadTimeout,requests.exceptions.RequestException) as e:
        traceback.format_exc()
        resp = None
    root = ET.fromstring(resp.content)
    articles = list(root.iter('Article'))
    if len(articles) == 0:
        return None
    article = articles[0]
    volume = article.findtext('Journal/JournalIssue/Volume')
    issue = article.findtext('Journal/JournalIssue/Issue')
    articledate = article.find("ArticleDate")
    if articledate is not None:
        year = articledate.findtext('Year')
    else:
        pubdate = article.find("Journal/JournalIssue/PubDate")
        if pubdate is not None:
            year = pubdate.findtext('Year')
    journal = article.findtext('Journal/Title')
    isoabbrev = article.findtext('Journal/ISOAbbreviation')
    
    if isoabbrev == "bioRxiv" and not volume and not issue:
        for elid in article.findall('ELocationID'):
            if elid.attrib.get('EIdType') == "pii":
                volume = elid.text

    doi = None
    for elid in article.findall("ELocationID"):
        if elid.attrib.get('EIdType') == "doi":
            doi = elid.text

    # Deal with italicized text in the titles
    title = extract_full_text(article.find("ArticleTitle"))
    ascii_title = unicodedata.normalize('NFKC', title)

    page = article.findtext("Pagination/MedlinePgn")
    authors = []
    for author in article.findall("AuthorList/Author"):
        lastname = author.findtext("LastName")
        forename = author.findtext("ForeName")
        initials = author.findtext("Initials")
        collective = author.findtext("CollectiveName")
        authordict = dict(lastname=lastname,forename=forename,initials=initials,collective=collective)
        for k in list(authordict):
            if not authordict.get(k):
                authordict[k] = None
            else:
                authordict['ascii_'+k] = unicodedata.normalize('NFKC', authordict[k])
        authors.append(authordict)

    details = dict(title=title,ascii_title=ascii_title,
                   journal=journal,journal_abbrev=isoabbrev,
                   issue=issue,volume=volume,year=year,
                   authors=authors,page=page,pmid=pmid,doi=doi)

    citation = format_citation(details)
    details['citation'] = citation
    details['ascii_citation'] = unicodedata.normalize('NFKC', citation)

    for k in list(details):
        if not details.get(k):
            details[k] = None
    return details

def format_citation(d):
    author_list = []
    for au in d['authors']:
        if au['lastname'] and au['initials']:
            author_list.append(au['lastname'] + " " + au['initials'])
        elif au['lastname']:
            author_list.append(au['lastname'])
        elif au['collective']:
            author_list.append(au['collective'])

    authors = ", ".join(author_list)
    title = d['title'].rstrip('.')
    rest = [ d['journal_abbrev'] ]
    if d['volume'] and d['issue']:
        rest.append("%(year)s;%(volume)s(%(issue)s)"%d)
    elif d['volume']:
        rest.append("%(year)s;%(volume)s"%d)
    else:
        rest.append("%(year)s"%d)
    if d['page']:
        rest[-1] += ":%(page)s"%d
    rest = " ".join(rest)
    return ". ".join([authors,title,rest]) + "."

if __name__ == "__main__":
    for doi in sys.argv[1:]:
        pmid = lookup(doi=doi)
        if pmid:
            print(doi,pmid['pmid'])
            pmid = pmid['pmid']
        else:
            pmid = doi
        print(citation_details(pmid))
